// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct SteamControllerState_t
	{
		public Int32 m_iPadding;
	};
	
	public enum ESteamControllerPad : int
	{
	};
	
}
