// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public enum ESteamFindFilter : int
	{
		eSteamFindLocalOnly = 0,
		eSteamFindRemoteOnly = 1,
		eSteamFindAll = 2,
	};
	
}
