// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTAPPS_INTERFACE_VERSION001")]
	public interface IClientApps
	{
		[VTableSlot(0)]
		Int32 GetAppData(UInt32 unAppID, string pchKey, StringBuilder pchValue, Int32 cchValueMax);
		[VTableSlot(1)]
		bool SetLocalAppConfig(UInt32 unAppID, Byte[] pchBuffer, Int32 cbBuffer);
		[VTableSlot(2)]
		UInt32 GetInternalAppIDFromGameID(CGameID nGameID);
		[VTableSlot(3)]
		Int32 GetAllOwnedMultiplayerApps(ref UInt32 punAppIDs, Int32 cAppIDsMax);
		[VTableSlot(4)]
		Int32 GetAppDataSection(UInt32 unAppID, EAppInfoSection eSection, Byte[] pchBuffer, Int32 cbBufferMax, bool bSharedKVSymbols);
		[VTableSlot(5)]
		bool RequestAppInfoUpdate(ref UInt32 pAppIDs, Int32 nNumAppIDs);
		[VTableSlot(6)]
		void NotifyAppEventTriggered(UInt32 unAppID, EAppEvent eAppEvent);
		[VTableSlot(7)]
		Int32 GetDLCCount(UInt32 unAppID);
		[VTableSlot(8)]
		bool BGetDLCDataByIndex(UInt32 unAppID, Int32 iDLC, ref UInt32 pDlcAppID, ref bool pbAvailable, StringBuilder pchName, Int32 cchNameBufferSize);
	};
}
