// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTSHORTCUTS_INTERFACE_VERSION001")]
	public interface IClientShortcuts
	{
		[VTableSlot(0)]
		UInt32 GetUniqueLocalAppId();
		[VTableSlot(1)]
		CGameID GetGameIDForAppID(UInt32 unAppID);
		[VTableSlot(2)]
		UInt32 GetAppIDForGameID(CGameID gameID);
		[VTableSlot(3)]
		UInt32 GetShortcutCount();
		[VTableSlot(4)]
		UInt32 GetShortcutAppIDByIndex(UInt32 uIndex);
		[VTableSlot(5)]
		string GetShortcutAppNameByIndex(UInt32 uIndex);
		[VTableSlot(6)]
		string GetShortcutExeByIndex(UInt32 uIndex);
		[VTableSlot(7)]
		UInt32 GetShortcutUserTagCountByIndex(UInt32 uIndex);
		[VTableSlot(8)]
		string GetShortcutUserTagByIndex(UInt32 uIndex, UInt32 arg1);
		[VTableSlot(9)]
		bool BIsShortcutRemoteByIndex(UInt32 uIndex);
		[VTableSlot(10)]
		string GetShortcutAppNameByAppID(UInt32 unAppID);
		[VTableSlot(11)]
		string GetShortcutExeByAppID(UInt32 unAppID);
		[VTableSlot(12)]
		string GetShortcutStartDirByAppID(UInt32 unAppID);
		[VTableSlot(13)]
		string GetShortcutIconByAppID(UInt32 unAppID);
		[VTableSlot(14)]
		UInt32 GetShortcutUserTagCountByAppID(UInt32 unAppID);
		[VTableSlot(15)]
		string GetShortcutUserTagByAppID(UInt32 unAppID, UInt32 arg1);
		[VTableSlot(16)]
		bool BIsShortcutRemoteByAppID(UInt32 unAppID);
		[VTableSlot(17)]
		UInt32 AddShortcut(string arg0, string arg1, string arg2);
		[VTableSlot(18)]
		void SetShortcutFromFullpath(UInt32 arg0, string arg1);
		[VTableSlot(19)]
		void SetShortcutAppName(UInt32 arg0, string arg1);
		[VTableSlot(20)]
		void SetShortcutExe(UInt32 arg0, string arg1);
		[VTableSlot(21)]
		void SetShortcutStartDir(UInt32 arg0, string arg1);
		[VTableSlot(22)]
		void SetShortcutIcon(UInt32 arg0, string arg1);
		[VTableSlot(23)]
		void ClearShortcutUserTags(UInt32 arg0);
		[VTableSlot(24)]
		void AddShortcutUserTag(UInt32 arg0, string arg1);
		[VTableSlot(25)]
		void RemoveShortcut(UInt32 arg0);
		[VTableSlot(26)]
		bool LaunchShortcut(UInt32 arg0);
	};
}
