// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public enum ENetworkDeviceState : int
	{
	};
	
	public enum EWirelessSecurityFlags : int
	{
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct WirelessAccessPoint_t
	{
		public Int32 m_iPadding;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct WirelessCredentials_t
	{
		public Int32 m_iPadding;
	};
	
	public enum ENetworkDeviceManagerError : int
	{
	};
	
	[InterfaceVersion("CLIENTNETWORKDEVICEMANAGER_INTERFACE_VERSION001")]
	public interface IClientNetworkDeviceManager
	{
		[VTableSlot(0)]
		bool IsInterfaceValid();
		[VTableSlot(1)]
		void RefreshDevices();
		[VTableSlot(2)]
		ENetworkDeviceState GetWirelessDeviceState();
		[VTableSlot(3)]
		Int32 GetWiredDeviceCount();
		[VTableSlot(4)]
		ENetworkDeviceState GetWiredDeviceState(Int32 iDevice);
		[VTableSlot(5)]
		bool IsWiredDevicePluggedIn(Int32 iDevice);
		[VTableSlot(6)]
		bool GetActiveWirelessAccessPoint(ref WirelessAccessPoint_t pAccessPoint);
		[VTableSlot(7)]
		bool EnumerateWirelessAccessPoints(ref WirelessAccessPoint_t pAccessPoint, UInt32 uUnk, ref UInt32 puUnk);
		[VTableSlot(8)]
		bool GetCachedCredentialsForSSID(string pchUnk, ref WirelessCredentials_t pCredentials);
		[VTableSlot(9)]
		EWirelessSecurityFlags GetPreferredSecurityMethod(UInt32 uUnk);
		[VTableSlot(10)]
		ENetworkDeviceManagerError ActivateWiredConnection(Int32 iConnection);
		[VTableSlot(11)]
		void DeactivateWiredConnection(Int32 iConnection);
		[VTableSlot(12)]
		ENetworkDeviceManagerError ConnectToAccessPoint(string pchUnk1, bool bUnk, EWirelessSecurityFlags eSecurityFlags, string pchUnk2);
		[VTableSlot(13)]
		void DisconnectFromAccessPoint();
	};
}
