// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTGAMESERVERSTATS_INTERFACE_VERSION001")]
	public interface IClientGameServerStats
	{
		[VTableSlot(0)]
		UInt64 RequestUserStats(CSteamID steamIDUser, CGameID gameID);
		[VTableSlot(1)]
		bool GetUserStat(CSteamID steamIDUser, CGameID gameID, string pchName, ref float pData);
		[VTableSlot(2)]
		bool GetUserStat(CSteamID steamIDUser, CGameID gameID, string pchName, ref Int32 pData);
		[VTableSlot(3)]
		bool GetUserAchievement(CSteamID steamIDUser, CGameID gameID, string pchName, ref bool pbAchieved, ref UInt32 prtTime);
		[VTableSlot(4)]
		bool SetUserStat(CSteamID steamIDUser, CGameID gameID, string pchName, float fData);
		[VTableSlot(5)]
		bool SetUserStat(CSteamID steamIDUser, CGameID gameID, string pchName, Int32 nData);
		[VTableSlot(6)]
		bool UpdateUserAvgRateStat(CSteamID steamIDUser, CGameID gameID, string pchName, float flCountThisSession, double dSessionLength);
		[VTableSlot(7)]
		bool SetUserAchievement(CSteamID steamIDUser, CGameID gameID, string pchName);
		[VTableSlot(8)]
		bool ClearUserAchievement(CSteamID steamIDUser, CGameID gameID, string pchName);
		[VTableSlot(9)]
		UInt64 StoreUserStats(CSteamID steamIDUser, CGameID gameID);
		[VTableSlot(10)]
		void SetMaxStatsLoaded(UInt32 uMax);
	};
}
