// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTSTREAMCLIENT_INTERFACE_VERSION001")]
	public interface IClientStreamClient
	{
		[VTableSlot(0)]
		void Launched(CGameID gameID);
		[VTableSlot(1)]
		void FocusGained(CGameID gameID, bool arg1);
		[VTableSlot(2)]
		void FocusLost(CGameID gameID);
		[VTableSlot(3)]
		void Finished(CGameID gameID, EResult eResult);
		[VTableSlot(4)]
		string GetSystemInfo();
		[VTableSlot(5)]
		void StartStreamingSession(CGameID gameID);
		[VTableSlot(6)]
		void ReportStreamingSessionEvent(CGameID gameID, string arg1);
		[VTableSlot(7)]
		void FinishStreamingSession(CGameID gameID, string arg1, string arg2);
	};
}
