// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTAPPMANAGER_INTERFACE_VERSION001")]
	public interface IClientAppManager
	{
		[VTableSlot(0)]
		EAppUpdateError InstallApp(UInt32 unAppID, string cszAppDir, Int32 iBaseFolder, bool bLegacy);
		[VTableSlot(1)]
		EAppUpdateError ConvertFromSteam2(UInt32 unAppID, string cszPath);
		[VTableSlot(2)]
		EAppUpdateError UninstallApp(UInt32 unAppID, bool bComplete);
		[VTableSlot(3)]
		EAppUpdateError LaunchApp(UInt32 unAppID, UInt32 uLaunchOption, string pszUserArgs);
		[VTableSlot(4)]
		bool ShutdownApp(UInt32 unAppID, bool bForce);
		[VTableSlot(5)]
		EAppState GetAppInstallState(UInt32 unAppID);
		[VTableSlot(6)]
		UInt32 GetAppBuildID(UInt32 unAppID);
		[VTableSlot(7)]
		bool GetAppSizeOnDisk(UInt32 unAppID, ref UInt64 pullAppSize, ref UInt64 pullUnk);
		[VTableSlot(8)]
		UInt32 GetAppInstallDir(UInt32 unAppID, StringBuilder pchPath, UInt32 cchPath);
		[VTableSlot(9)]
		bool IsAppDlcInstalled(UInt32 unAppID, UInt32 unDLCAppID);
		[VTableSlot(10)]
		UInt32 GetNumInstalledApps();
		[VTableSlot(11)]
		UInt32 GetInstalledApps(ref UInt32 punAppIDs, UInt32 cAppIDsMax);
		[VTableSlot(12)]
		UInt32 GetAppDependency(UInt32 unAppID);
		[VTableSlot(13)]
		UInt32 GetDependentApps(UInt32 unAppID, ref UInt32 punAppIDs, Int32 cAppIDsMax);
		[VTableSlot(14)]
		UInt32 GetUpdateInfo(UInt32 unAppID, ref AppUpdateInfo_s pUpdateInfo);
		[VTableSlot(15)]
		bool SetContentLocked(UInt32 unAppID, bool bLockContent);
		[VTableSlot(16)]
		bool SetAppConfig(UInt32 unAppID, Byte[] pchBuffer, Int32 cbBuffer, bool bSharedKVSymbols);
		[VTableSlot(17)]
		Int32 GetAppConfigValue(UInt32 unAppID, string pchKey, StringBuilder pchValue, Int32 cchValueMax);
		[VTableSlot(18)]
		bool SetAppConfigValue(UInt32 unAppID, string pchKey, string pchValue);
		[VTableSlot(19)]
		bool BIsAppUpToDate(UInt32 unAppID);
		[VTableSlot(20)]
		UInt32 GetAvailableLaunchOptions(UInt32 unAppID, ref UInt32 puOptions, UInt32 cuOptionsMax);
		[VTableSlot(21)]
		UInt32 GetAvailableLanguages(UInt32 unAppID, bool arg1, StringBuilder pchLanguages, UInt32 cchLanguagesMax);
		[VTableSlot(22)]
		bool StartValidatingApp(UInt32 unAppID);
		[VTableSlot(23)]
		bool MarkContentCorrupt(UInt32 unAppID, bool bCorrupt);
		[VTableSlot(24)]
		UInt32 GetInstalledDepots(UInt32 unAppID, ref UInt32 puDepots, UInt32 cuDepotsMax);
		[VTableSlot(25)]
		bool BCacheBetaPassword(UInt32 unAppID, string cszBetaKey, string cszBetaPassword);
		[VTableSlot(26)]
		bool BRequestBetaPasswords(UInt32 unAppID);
		[VTableSlot(27)]
		bool BIsCachedBetaPasswordValid(UInt32 unAppID, string cszBetaKey);
		[VTableSlot(28)]
		bool SetDownloadingEnabled(bool bState);
		[VTableSlot(29)]
		bool BIsDownloadingEnabled();
		[VTableSlot(30)]
		bool GetDownloadStats(ref DownloadStats_s pDownloadStats);
		[VTableSlot(31)]
		UInt32 GetDownloadingAppID();
		[VTableSlot(32)]
		bool ChangeAppPriority(UInt32 unAppID, EAppDownloadPriority ePriority);
		[VTableSlot(33)]
		bool BHasLocalContentServer();
		[VTableSlot(34)]
		bool BuildBackup(UInt32 unAppID, UInt64 ullMaxFileSize, string cszBackupPath);
		[VTableSlot(35)]
		bool BuildInstaller(string cszProjectFile, string cszBackupPath, string arg2);
		[VTableSlot(36)]
		bool CancelBackup();
		[VTableSlot(37)]
		EAppUpdateError RestoreApp(UInt32 unAppID, Int32 iBaseFolder, string cszBackupPath);
		[VTableSlot(38)]
		bool BNeedsFile(UInt32 unAppID, string cszFilePath, UInt64 ullFileSize, UInt32 uUnk);
		[VTableSlot(39)]
		bool BAddFileOnDisk(UInt32 unAppID, string cszFilePath, UInt64 ullFileSize, UInt32 uUnk, SHADigestWrapper_t ubSha1);
		[VTableSlot(40)]
		UInt32 FinishAddingFiles(UInt32 unAppID);
		[VTableSlot(41)]
		bool GetAppStateInfo(UInt32 unAppID, ref EAppReleaseState peReleaseState, ref EAppOwernshipFlags peOwernshipFlags, ref EAppState peAppState);
		[VTableSlot(42)]
		Int32 GetNumInstallBaseFolders();
		[VTableSlot(43)]
		Int32 GetInstallBaseFolder(Int32 iBaseFolder, StringBuilder pchPath, Int32 cbPath);
		[VTableSlot(44)]
		Int32 AddInstallBaseFolder(string szPath);
		[VTableSlot(45)]
		bool RemoveInstallBaseFolder(Int32 iBaseFolder);
		[VTableSlot(46)]
		UInt64 GetFreeDiskSpace(Int32 iBaseFolder);
		[VTableSlot(47)]
		Int32 GetAppInstallBaseFolder(Int32 iBaseFolder);
		[VTableSlot(48)]
		void ForceInstallDirOverride(string cszPath);
		[VTableSlot(49)]
		bool SetDownloadThrottleRateKbps(Int32 iRate);
		[VTableSlot(50)]
		Int32 GetDownloadThrottleRateKbps();
		[VTableSlot(51)]
		void SuspendDownloadThrottling(bool bSuspend);
		[VTableSlot(52)]
		bool GetAppOwner(UInt32 uUnk1, ref CSteamID pUnk, StringBuilder szUnk, UInt32 uUnk2);
	};
}
