// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTMASTERSERVERUPDATER_INTERFACE_VERSION001")]
	public interface IClientMasterServerUpdater
	{
		[VTableSlot(0)]
		void SetActive(bool bActive);
		[VTableSlot(1)]
		void SetHeartbeatInterval(Int32 iHeartbeatInterval);
		[VTableSlot(2)]
		bool HandleIncomingPacket(Byte[] pData, Int32 cbData, UInt32 srcIP, UInt16 srcPort);
		[VTableSlot(3)]
		Int32 GetNextOutgoingPacket(Byte[] pOut, Int32 cbMaxOut, ref UInt32 pNetAdr, ref UInt16 pPort);
		[VTableSlot(4)]
		void SetBasicServerData(UInt16 nProtocolVersion, bool bDedicatedServer, string pRegionName, string pProductName, UInt16 nMaxReportedClients, bool bPasswordProtected, string pGameDescription);
		[VTableSlot(5)]
		void ClearAllKeyValues();
		[VTableSlot(6)]
		void SetKeyValue(string pKey, string pValue);
		[VTableSlot(7)]
		void NotifyShutdown();
		[VTableSlot(8)]
		bool WasRestartRequested();
		[VTableSlot(9)]
		void ForceHeartbeat();
		[VTableSlot(10)]
		bool AddMasterServer(string pServerAddress);
		[VTableSlot(11)]
		bool RemoveMasterServer(string pServerAddress);
		[VTableSlot(12)]
		Int32 GetNumMasterServers();
		[VTableSlot(13)]
		Int32 GetMasterServerAddress(Int32 iServer, StringBuilder pOut, Int32 outBufferSize);
	};
}
