// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTUGC_INTERFACE_VERSION001")]
	public interface IClientUGC
	{
		[VTableSlot(0)]
		UInt64 CreateQueryUserUGCRequest(UInt32 unAccountID, EUserUGCList eListType, EUGCMatchingUGCType eMatchingUGCType, EUserUGCListSortOrder eSortOrder, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage);
		[VTableSlot(1)]
		UInt64 CreateQueryAllUGCRequest(EUGCQuery eQueryType, EUGCMatchingUGCType eMatchingeMatchingUGCTypeFileType, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage);
		[VTableSlot(2)]
		UInt64 SendQueryUGCRequest(UInt64 handle);
		[VTableSlot(3)]
		bool GetQueryUGCResult(UInt64 handle, UInt32 index, ref SteamUGCDetails_t pDetails);
		[VTableSlot(4)]
		bool ReleaseQueryUGCRequest(UInt64 handle);
		[VTableSlot(5)]
		bool AddRequiredTag(UInt64 handle, string pTagName);
		[VTableSlot(6)]
		bool AddExcludedTag(UInt64 handle, string pTagName);
		[VTableSlot(7)]
		bool SetReturnLongDescription(UInt64 handle, bool bReturnLongDescription);
		[VTableSlot(8)]
		bool SetReturnTotalOnly(UInt64 handle, bool bReturnTotalOnly);
		[VTableSlot(9)]
		bool SetAllowCachedResponse(UInt64 handle, UInt32 arg1);
		[VTableSlot(10)]
		bool SetCloudFileNameFilter(UInt64 handle, string pMatchCloudFileName);
		[VTableSlot(11)]
		bool SetMatchAnyTag(UInt64 handle, bool bMatchAnyTag);
		[VTableSlot(12)]
		bool SetSearchText(UInt64 handle, string pSearchText);
		[VTableSlot(13)]
		bool SetRankedByTrendDays(UInt64 handle, UInt32 unDays);
		[VTableSlot(14)]
		UInt64 RequestUGCDetails(UInt64 nPublishedFileID);
		[VTableSlot(15)]
		UInt64 CreateItem(UInt32 arg0, EWorkshopFileType arg1);
		[VTableSlot(16)]
		UInt64 UploadItemContent(UInt64 arg0, string arg1);
		[VTableSlot(17)]
		UInt64 UploadItemPreview(UInt64 arg0, string arg1);
		[VTableSlot(18)]
		UInt64 StartItemUpdate(UInt32 arg0, UInt64 arg1);
		[VTableSlot(19)]
		bool SetItemTitle(UInt64 arg0, string arg1);
		[VTableSlot(20)]
		bool SetItemChangeDescription(UInt64 arg0, string arg1);
		[VTableSlot(21)]
		bool SetItemDescription(UInt64 arg0, string arg1);
		[VTableSlot(22)]
		bool SetItemVisibility(UInt64 arg0, ERemoteStoragePublishedFileVisibility arg1);
		[VTableSlot(23)]
		bool SetItemTags(UInt64 arg0, ref SteamParamStringArray_t arg1);
		[VTableSlot(24)]
		bool SetItemContent(UInt64 arg0, UInt64 arg1);
		[VTableSlot(25)]
		bool SetItemPreview(UInt64 arg0, UInt64 arg1);
		[VTableSlot(26)]
		UInt64 CommitItemUpdate(UInt64 arg0);
		[VTableSlot(27)]
		UInt64 SubscribeItem(UInt32 arg0, UInt64 arg1);
		[VTableSlot(28)]
		UInt64 UnsubscribeItem(UInt32 arg0, UInt64 arg1);
		[VTableSlot(29)]
		UInt32 GetNumSubscribedItems(UInt32 arg0);
		[VTableSlot(30)]
		UInt32 GetSubscribedItems(UInt32 arg0, ref UInt64 arg1, UInt32 arg2);
		[VTableSlot(31)]
		bool GetSubscribedItemInfo(UInt32 arg0, UInt64 arg1, StringBuilder arg2, Int32 arg3, StringBuilder arg4, Int32 arg5, ref EWorkshopFileType arg6, ref bool arg7, StringBuilder arg8, Int32 arg9, ref UInt64 arg10);
	};
}
