// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTAUDIO_INTERFACE_VERSION001")]
	public interface IClientAudio
	{
		[VTableSlot(0)]
		void StartVoiceRecording();
		[VTableSlot(1)]
		void StopVoiceRecording();
		[VTableSlot(2)]
		void ResetVoiceRecording();
		[VTableSlot(3)]
		EVoiceResult GetAvailableVoice(ref UInt32 pcbCompressed, ref UInt32 pcbUncompressed, UInt32 nUncompressedVoiceDesiredSampleRate);
		[VTableSlot(4)]
		EVoiceResult GetVoice(bool bWantCompressed, Byte[] pDestBuffer, UInt32 cbDestBufferSize, ref UInt32 nBytesWritten, bool bWantUncompressed, Byte[] pUncompressedDestBuffer, UInt32 cbUncompressedDestBufferSize, ref UInt32 nUncompressBytesWritten, UInt32 nUncompressedVoiceDesiredSampleRate);
		[VTableSlot(5)]
		EVoiceResult GetCompressedVoice(Byte[] pDestBuffer, UInt32 cbDestBufferSize, ref UInt32 nBytesWritten);
		[VTableSlot(6)]
		EVoiceResult DecompressVoice(Byte[] pCompressed, UInt32 cbCompressed, Byte[] pDestBuffer, UInt32 cbDestBufferSize, ref UInt32 nBytesWritten, UInt32 nDesiredSampleRate);
		[VTableSlot(7)]
		UInt32 GetVoiceOptimalSampleRate();
	};
}
