// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTGAMESTATS_INTERFACE_VERSION001")]
	public interface IClientGameStats
	{
		[VTableSlot(0)]
		UInt64 GetNewSession(SByte nAccountType, UInt64 ullAccountID, UInt32 nAppID, UInt32 rtTimeStarted);
		[VTableSlot(1)]
		UInt64 EndSession(UInt64 ulSessionID, UInt32 rtTimeEnded, Int16 nReasonCode);
		[VTableSlot(2)]
		EResult AddSessionAttributeInt(UInt64 ulSessionID, string pstrName, Int32 nData);
		[VTableSlot(3)]
		EResult AddSessionAttributeString(UInt64 ulSessionID, string pstrName, string pstrData);
		[VTableSlot(4)]
		EResult AddSessionAttributeFloat(UInt64 ulSessionID, string pstrName, float fData);
		[VTableSlot(5)]
		EResult AddNewRow(ref UInt64 pulRowID, UInt64 ulSessionID, string pstrTableName);
		[VTableSlot(6)]
		EResult CommitRow(UInt64 ulRowID);
		[VTableSlot(7)]
		EResult CommitOutstandingRows(UInt64 ulSessionID);
		[VTableSlot(8)]
		EResult AddRowAttributeInt(UInt64 ulRowID, string pstrName, Int32 iData);
		[VTableSlot(9)]
		EResult AddRowAtributeString(UInt64 ulRowID, string pstrName, string pstrData);
		[VTableSlot(10)]
		EResult AddRowAttributeFloat(UInt64 ulRowID, string pstrName, float fData);
		[VTableSlot(11)]
		EResult AddSessionAttributeInt64(UInt64 ulSessionID, string pstrName, Int64 llData);
		[VTableSlot(12)]
		EResult AddRowAttributeInt64(UInt64 ulRowID, string pstrName, Int64 llData);
		[VTableSlot(13)]
		EResult ReportString(UInt64 ulSessionID, Int32 iSeverity, string cszFormat);
		[VTableSlot(14)]
		EResult _ReportString(UInt64 ulSessionID, Int32 arg1, string arg2, Int32 arg3, Byte[] arg4);
		[VTableSlot(15)]
		EResult ReportStringAccumulated(UInt64 ulSessionID, Int32 iSeverity, string cszFormat);
		[VTableSlot(16)]
		EResult _ReportStringAccumulated(UInt64 ulSessionID, Int32 arg1, string arg2, Int32 arg3, Byte[] arg4);
		[VTableSlot(17)]
		EResult ReportBugScreenshot(UInt64 ulSessionID, string szBugText, Int32 cubScreenshot, Byte[] pubScreenshot);
	};
}
