// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public enum MusicPlayback_Status : int
	{
	};
	
	public enum MediaController_Status : int
	{
	};
	
	[InterfaceVersion("CLIENTMUSIC_INTERFACE_VERSION001")]
	public interface IClientMusic
	{
		[VTableSlot(0)]
		Int32 GetQueueCount();
		[VTableSlot(1)]
		CMusicQueueEntry GetQueueEntry(Int32 arg0);
		[VTableSlot(2)]
		void LoadQueueEntry(Int32 arg0);
		[VTableSlot(3)]
		void AddQueueEntry(ref CMusicQueueEntry arg0);
		[VTableSlot(4)]
		void RemoveQueueEntry(ref CMusicQueueEntry arg0);
		[VTableSlot(5)]
		MusicPlayback_Status GetPlaybackStatus();
		[VTableSlot(6)]
		void Play();
		[VTableSlot(7)]
		void Pause();
		[VTableSlot(8)]
		void Stop();
		[VTableSlot(9)]
		void PlayFirst();
		[VTableSlot(10)]
		void PlayPrevious();
		[VTableSlot(11)]
		void PlayNext();
		[VTableSlot(12)]
		void PlayLast();
		[VTableSlot(13)]
		MediaController_Status GetStatusLocalLibrary();
		[VTableSlot(14)]
		Int32 GetLocalLibraryDirectoryEntryCount();
		[VTableSlot(15)]
		bool GetLocalLibraryDirectoryEntry(Int32 arg0, ref Int32 arg1, StringBuilder arg2, Int32 arg3, StringBuilder arg4, Int32 arg5, ref bool arg6);
		[VTableSlot(16)]
		void SetLocalLibraryDirectoryEntryEnabled(Int32 arg0, bool arg1);
		[VTableSlot(17)]
		void ResetLocalLibraryDirectoriesToDefault();
		[VTableSlot(18)]
		void UpdateLocalLibraryDirectoriesToCrawl();
		[VTableSlot(19)]
		bool BLocalLibraryIsCrawling();
		[VTableSlot(20)]
		Int32 GetLocalLibraryAlbumCount();
		[VTableSlot(21)]
		bool GetLocalLibraryAlbumKey(Int32 arg0, StringBuilder arg1, Int32 arg2);
		[VTableSlot(22)]
		bool GetLocalLibraryAlbumNextKey(string arg0, bool arg1, StringBuilder arg2, Int32 arg3);
		[VTableSlot(23)]
		bool GetLocalLibraryAlbumEntry(string arg0, StringBuilder arg1, Int32 arg2, StringBuilder arg3, Int32 arg4, ref Int32 arg5);
		[VTableSlot(24)]
		bool GetLocalLibraryAlbumTrackEntry(string arg0, Int32 arg1, StringBuilder arg2, Int32 arg3, ref Int32 arg4);
		[VTableSlot(25)]
		bool GetLocalLibraryAlbumTrackKey(string arg0, Int32 arg1, StringBuilder arg2, Int32 arg3);
		[VTableSlot(26)]
		void StartUsingSpotify();
		[VTableSlot(27)]
		void StopUsingSpotify();
		[VTableSlot(28)]
		MediaController_Status GetStatusSpotify();
		[VTableSlot(29)]
		void LoginSpotify(string arg0, string arg1);
		[VTableSlot(30)]
		void ReloginSpotify();
		[VTableSlot(31)]
		string GetCurrentUserSpotify();
		[VTableSlot(32)]
		void ForgetCurrentUserSpotify();
		[VTableSlot(33)]
		void LogoutSpotify();
		[VTableSlot(34)]
		void DumpStatusToConsole();
	};
}
