// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTDEVICEAUTH_INTERFACE_VERSION001")]
	public interface IClientDeviceAuth
	{
		[VTableSlot(0)]
		UInt64 AuthorizeLocalDevice(string pubUnk, UInt32 cubUnk);
		[VTableSlot(1)]
		UInt64 DeauthorizeLocalDevice(UInt32 uUnk);
		[VTableSlot(2)]
		UInt32 GetDeviceAuthorizations(ref UInt64 puUnk, UInt32 uUnk);
		[VTableSlot(3)]
		bool GetDeviceAuthorizationInfo(UInt64 uUnk, ref UInt32 puUnk1, ref UInt32 puUnk2, ref UInt32 puUnk3, ref bool pbUnk, StringBuilder pszUnk1, Int32 iUnk1, StringBuilder pszUnk2, Int32 iUnk2, StringBuilder pszUnk3, Int32 iUnk3);
		[VTableSlot(4)]
		UInt64 RequestAuthorizedDevicesInfo();
		[VTableSlot(5)]
		bool BIsAuthorizedLender(UInt32 uUnk);
		[VTableSlot(6)]
		UInt32 GetSharedLibraryLockedBy(UInt32 uUnk);
	};
}
