// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTUNIFIEDMESSAGES_INTERFACE_VERSION001")]
	public interface IClientUnifiedMessages
	{
		[VTableSlot(0)]
		UInt64 SendMethod(string arg0, Byte[] arg1, UInt32 arg2, UInt64 arg3);
		[VTableSlot(1)]
		bool GetMethodResponseInfo(UInt64 arg0, ref UInt32 arg1, ref EResult arg2);
		[VTableSlot(2)]
		bool GetMethodResponseData(UInt64 arg0, Byte[] arg1, UInt32 arg2, bool arg3);
		[VTableSlot(3)]
		bool ReleaseMethod(UInt64 arg0);
		[VTableSlot(4)]
		bool SendNotification(string arg0, Byte[] arg1, UInt32 arg2);
	};
}
