// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTSTREAMLAUNCHER_INTERFACE_VERSION001")]
	public interface IClientStreamLauncher
	{
		[VTableSlot(0)]
		EStreamLauncherResult StartStreaming(string cszFilePath);
		[VTableSlot(1)]
		void StopStreaming();
	};
}
