// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMMUSIC_INTERFACE_VERSION001")]
	public interface ISteamMusic001
	{
		[VTableSlot(0)]
		bool BIsEnabled();
		[VTableSlot(1)]
		bool BIsPlaying();
		[VTableSlot(2)]
		AudioPlayback_Status GetPlaybackStatus();
		[VTableSlot(3)]
		void Play();
		[VTableSlot(4)]
		void Pause();
		[VTableSlot(5)]
		void PlayPrevious();
		[VTableSlot(6)]
		void PlayNext();
		[VTableSlot(7)]
		void SetVolume(float flVolume);
		[VTableSlot(8)]
		float GetVolume();
	};
}
