// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamGameServerStats001")]
	public interface ISteamGameServerStats001
	{
		[VTableSlot(0)]
		UInt64 RequestUserStats(CSteamID steamIDUser);
		[VTableSlot(1)]
		bool GetUserStat(CSteamID steamIDUser, string pchName, ref float pData);
		[VTableSlot(2)]
		bool GetUserStat(CSteamID steamIDUser, string pchName, ref Int32 pData);
		[VTableSlot(3)]
		bool GetUserAchievement(CSteamID steamIDUser, string pchName, ref bool pbAchieved);
		[VTableSlot(4)]
		bool SetUserStat(CSteamID steamIDUser, string pchName, float fData);
		[VTableSlot(5)]
		bool SetUserStat(CSteamID steamIDUser, string pchName, Int32 nData);
		[VTableSlot(6)]
		bool UpdateUserAvgRateStat(CSteamID steamIDUser, string pchName, float flCountThisSession, double dSessionLength);
		[VTableSlot(7)]
		bool SetUserAchievement(CSteamID steamIDUser, string pchName);
		[VTableSlot(8)]
		bool ClearUserAchievement(CSteamID steamIDUser, string pchName);
		[VTableSlot(9)]
		UInt64 StoreUserStats(CSteamID steamIDUser);
	};
}
