// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamUtils004")]
	public interface ISteamUtils004
	{
		[VTableSlot(0)]
		UInt32 GetSecondsSinceAppActive();
		[VTableSlot(1)]
		UInt32 GetSecondsSinceComputerActive();
		[VTableSlot(2)]
		EUniverse GetConnectedUniverse();
		[VTableSlot(3)]
		UInt32 GetServerRealTime();
		[VTableSlot(4)]
		string GetIPCountry();
		[VTableSlot(5)]
		bool GetImageSize(Int32 iImage, ref UInt32 pnWidth, ref UInt32 pnHeight);
		[VTableSlot(6)]
		bool GetImageRGBA(Int32 iImage, Byte[] pubDest, Int32 nDestBufferSize);
		[VTableSlot(7)]
		bool GetCSERIPPort(ref UInt32 unIP, ref UInt16 usPort);
		[VTableSlot(8)]
		Byte GetCurrentBatteryPower();
		[VTableSlot(9)]
		UInt32 GetAppID();
		[VTableSlot(10)]
		void SetOverlayNotificationPosition(ENotificationPosition eNotificationPosition);
		[VTableSlot(11)]
		bool IsAPICallCompleted(UInt64 hSteamAPICall, ref bool pbFailed);
		[VTableSlot(12)]
		ESteamAPICallFailure GetAPICallFailureReason(UInt64 hSteamAPICall);
		[VTableSlot(13)]
		bool GetAPICallResult(UInt64 hSteamAPICall, Byte[] pCallback, Int32 cubCallback, Int32 iCallbackExpected, ref bool pbFailed);
		[VTableSlot(14)]
		void RunFrame();
		[VTableSlot(15)]
		UInt32 GetIPCCallCount();
		[VTableSlot(16)]
		void SetWarningMessageHook(ref IntPtr pFunction);
		[VTableSlot(17)]
		bool IsOverlayEnabled();
	};
}
