// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMUSERSTATS_INTERFACE_VERSION004")]
	public interface ISteamUserStats004
	{
		[VTableSlot(0)]
		bool RequestCurrentStats();
		[VTableSlot(1)]
		bool GetStat(string pchName, ref float pData);
		[VTableSlot(2)]
		bool GetStat(string pchName, ref Int32 pData);
		[VTableSlot(3)]
		bool SetStat(string pchName, float fData);
		[VTableSlot(4)]
		bool SetStat(string pchName, Int32 nData);
		[VTableSlot(5)]
		bool UpdateAvgRateStat(string pchName, float arg1, double dSessionLength);
		[VTableSlot(6)]
		bool GetAchievement(string pchName, ref bool pbAchieved);
		[VTableSlot(7)]
		bool SetAchievement(string pchName);
		[VTableSlot(8)]
		bool ClearAchievement(string pchName);
		[VTableSlot(9)]
		bool StoreStats();
		[VTableSlot(10)]
		Int32 GetAchievementIcon(string pchName);
		[VTableSlot(11)]
		string GetAchievementDisplayAttribute(string pchName, string pchKey);
		[VTableSlot(12)]
		bool IndicateAchievementProgress(string pchName, UInt32 nCurProgress, UInt32 nMaxProgress);
		[VTableSlot(13)]
		UInt64 RequestUserStats(CSteamID steamIDUser);
		[VTableSlot(14)]
		bool GetUserStat(CSteamID steamIDUser, string pchName, ref float pData);
		[VTableSlot(15)]
		bool GetUserStat(CSteamID steamIDUser, string pchName, ref Int32 pData);
		[VTableSlot(16)]
		bool GetUserAchievement(CSteamID steamIDUser, string pchName, ref bool pbAchieved);
		[VTableSlot(17)]
		bool ResetAllStats(bool bAchievementsToo);
	};
}
