// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamGameStats001")]
	public interface ISteamGameStats001
	{
		[VTableSlot(0)]
		UInt64 GetNewSession(SByte nAccountType, UInt64 ulAccountID, Int32 nAppID, UInt32 rtTimeStarted);
		[VTableSlot(1)]
		UInt64 EndSession(UInt64 ulSessionID, UInt32 rtTimeEnded, Int32 nReasonCode);
		[VTableSlot(2)]
		EResult AddSessionAttributeInt(UInt64 ulSessionID, string pstrName, Int32 nData);
		[VTableSlot(3)]
		EResult AddSessionAttributeString(UInt64 ulSessionID, string pstrName, string pstrData);
		[VTableSlot(4)]
		EResult AddSessionAttributeFloat(UInt64 ulSessionID, string pstrName, float fData);
		[VTableSlot(5)]
		EResult AddNewRow(ref UInt64 pulRowID, UInt64 ulSessionID, string pstrTableName);
		[VTableSlot(6)]
		EResult CommitRow(UInt64 ulRowID);
		[VTableSlot(7)]
		EResult CommitOutstandingRows(UInt64 ulSessionID);
		[VTableSlot(8)]
		EResult AddRowAttributeInt(UInt64 ulRowID, string pstrName, Int32 nData);
		[VTableSlot(9)]
		EResult AddRowAtributeString(UInt64 ulRowID, string pstrName, string pstrData);
		[VTableSlot(10)]
		EResult AddRowAttributeFloat(UInt64 ulRowID, string pstrName, float fData);
		[VTableSlot(11)]
		EResult AddSessionAttributeInt64(UInt64 ulSessionID, string pstrName, Int64 llData);
		[VTableSlot(12)]
		EResult AddRowAttributeInt64(UInt64 ulRowID, string pstrName, Int64 llData);
	};
}
