// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMAPPTICKET_INTERFACE_VERSION001")]
	public interface ISteamAppTicket001
	{
		[VTableSlot(0)]
		UInt32 GetAppOwnershipTicketData(UInt32 nAppId, Byte[] pvSignedTicket, UInt32 cbSignedTicket, ref UInt32 piAppId, ref UInt32 piSteamId, ref UInt32 piSignature, ref UInt32 pcbSignature);
	};
}
