// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamUser010")]
	public interface ISteamUser010
	{
		[VTableSlot(0)]
		Int32 GetHSteamUser();
		[VTableSlot(1)]
		bool BLoggedOn();
		[VTableSlot(2)]
		CSteamID GetSteamID();
		[VTableSlot(3)]
		Int32 InitiateGameConnection(Byte[] pBlob, Int32 cbMaxBlob, CSteamID steamID, UInt32 unIPServer, UInt16 usPortServer, bool bSecure);
		[VTableSlot(4)]
		void TerminateGameConnection(UInt32 unIPServer, UInt16 usPortServer);
		[VTableSlot(5)]
		void TrackAppUsageEvent(CGameID gameID, EAppUsageEvent eAppUsageEvent, string pchExtraInfo);
	};
}
