// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamMatchMaking001")]
	public interface ISteamMatchmaking001
	{
		[VTableSlot(0)]
		Int32 GetFavoriteGameCount();
		[VTableSlot(1)]
		bool GetFavoriteGame(Int32 iGame, ref UInt32 pnAppID, ref UInt32 pnIP, ref UInt16 pnConnPort, ref UInt32 punFlags, ref UInt32 pRTime32LastPlayedOnServer);
		[VTableSlot(2)]
		Int32 AddFavoriteGame(UInt32 nAppID, UInt32 nIP, UInt16 nConnPort, UInt32 unFlags, UInt32 rTime32LastPlayedOnServer);
		[VTableSlot(3)]
		bool RemoveFavoriteGame(UInt32 nAppID, UInt32 nIP, UInt16 nConnPort, UInt32 unFlags);
		[VTableSlot(4)]
		bool GetFavoriteGame2(Int32 iGame, ref UInt32 pnAppID, ref UInt32 pnIP, ref UInt16 pnConnPort, ref UInt16 pnQueryPort, ref UInt32 punFlags, ref UInt32 pRTime32LastPlayedOnServer);
		[VTableSlot(5)]
		Int32 AddFavoriteGame2(UInt32 nAppID, UInt32 nIP, UInt16 nConnPort, UInt16 nQueryPort, UInt32 unFlags, UInt32 rTime32LastPlayedOnServer);
		[VTableSlot(6)]
		bool RemoveFavoriteGame2(UInt32 nAppID, UInt32 nIP, UInt16 nConnPort, UInt16 nQueryPort, UInt32 unFlags);
		[VTableSlot(7)]
		void RequestLobbyList(UInt64 ulGameID, ref MatchMakingKeyValuePair_t pFilters, UInt32 nFilters);
		[VTableSlot(8)]
		CSteamID GetLobbyByIndex(Int32 iLobby);
		[VTableSlot(9)]
		void CreateLobby(UInt64 ulGameID, bool bPrivate);
		[VTableSlot(10)]
		void JoinLobby(CSteamID steamIDLobby);
		[VTableSlot(11)]
		void LeaveLobby(CSteamID steamIDLobby);
		[VTableSlot(12)]
		bool InviteUserToLobby(CSteamID steamIDLobby, CSteamID steamIDInvitee);
		[VTableSlot(13)]
		Int32 GetNumLobbyMembers(CSteamID steamIDLobby);
		[VTableSlot(14)]
		CSteamID GetLobbyMemberByIndex(CSteamID steamIDLobby, Int32 iMember);
		[VTableSlot(15)]
		string GetLobbyData(CSteamID SteamIDLobby, string pchKey);
		[VTableSlot(16)]
		void SetLobbyData(CSteamID steamIDLobby, string pchKey, string pchValue);
		[VTableSlot(17)]
		string GetLobbyMemberData(CSteamID steamIDLobby, CSteamID steamIDUser, string pchKey);
		[VTableSlot(18)]
		void SetLobbyMemberData(CSteamID steamIDLobby, string pchKey, string pchValue);
		[VTableSlot(19)]
		void ChangeLobbyAdmin(CSteamID steamIDLobby, CSteamID steamIDNewAdmin);
		[VTableSlot(20)]
		bool SendLobbyChatMsg(CSteamID steamIDLobby, Byte[] pvMsgBody, Int32 cubMsgBody);
		[VTableSlot(21)]
		Int32 GetLobbyChatEntry(CSteamID steamIDLobby, Int32 iChatID, ref CSteamID pSteamIDUser, Byte[] pvData, Int32 cubData, ref EChatEntryType peChatEntryType);
		[VTableSlot(22)]
		bool RequestLobbyData(CSteamID steamIDLobby);
	};
}
