// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamGameServer004")]
	public interface ISteamGameServer004
	{
		[VTableSlot(0)]
		void LogOn();
		[VTableSlot(1)]
		void LogOff();
		[VTableSlot(2)]
		bool BLoggedOn();
		[VTableSlot(3)]
		bool BSecure();
		[VTableSlot(4)]
		CSteamID GetSteamID();
		[VTableSlot(5)]
		bool SendUserConnectAndAuthenticate(CSteamID steamIDUser, UInt32 arg1, Byte[] arg2, UInt32 arg3);
		[VTableSlot(6)]
		CSteamID CreateUnauthenticatedUserConnection();
		[VTableSlot(7)]
		void SendUserDisconnect(CSteamID steamIDUser);
		[VTableSlot(8)]
		bool BUpdateUserData(CSteamID steamIDUser, string pchPlayerName, UInt32 uScore);
		[VTableSlot(9)]
		bool BSetServerType(Int32 nGameAppId, UInt32 unServerFlags, UInt32 unGameIP, UInt16 unGamePort, UInt16 usSpectatorPort, UInt16 usQueryPort, string pchGameDir, string pchVersion, bool bLANMode);
		[VTableSlot(10)]
		bool UpdateStatus(Int32 cPlayers, Int32 cPlayersMax, Int32 cBotPlayers, string pchServerName, string pSpectatorServerName, string pchMapName);
		[VTableSlot(11)]
		void UpdateSpectatorPort(UInt16 unSpectatorPort);
		[VTableSlot(12)]
		void SetGameType(string pchGameType);
		[VTableSlot(13)]
		bool BGetUserAchievementStatus(CSteamID steamID, string pchAchievementName);
	};
}
