// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMREMOTESTORAGE_INTERFACE_VERSION001")]
	public interface ISteamRemoteStorage001
	{
		[VTableSlot(0)]
		bool FileWrite(string filename, Byte[] data, Int32 arg2);
		[VTableSlot(1)]
		UInt32 GetFileSize(string filename);
		[VTableSlot(2)]
		bool FileRead(string filename, Byte[] buffer, Int32 size);
		[VTableSlot(3)]
		bool FileExists(string filename);
		[VTableSlot(4)]
		bool FileDelete(string filename);
		[VTableSlot(5)]
		UInt32 GetFileCount();
		[VTableSlot(6)]
		string GetFileNameAndSize(Int32 index, ref Int32 size);
		[VTableSlot(7)]
		bool GetQuota(ref Int32 current, ref Int32 maximum);
	};
}
