// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMAPPLIST_INTERFACE_VERSION001")]
	public interface ISteamAppList001
	{
		[VTableSlot(0)]
		Int32 GetNumInstalledApps();
		[VTableSlot(1)]
		Int32 GetInstalledApps(ref UInt32 puUnk, UInt32 uUnk);
		[VTableSlot(2)]
		Int32 GetAppName(UInt32 uUnk, StringBuilder pUnk, Int32 iUnk);
		[VTableSlot(3)]
		Int32 GetAppInstallDir(UInt32 uUnk, StringBuilder pUnk, Int32 iUnk);
		[VTableSlot(4)]
		Int32 GetAppBuildId(UInt32 uUnk);
	};
}
