// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMAPPS_INTERFACE_VERSION001")]
	public interface ISteamApps001
	{
		[VTableSlot(0)]
		Int32 GetAppData(UInt32 nAppID, string pchKey, StringBuilder pchValue, Int32 cchValueMax);
	};
}
