// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMUGC_INTERFACE_VERSION001")]
	public interface ISteamUGC001
	{
		[VTableSlot(0)]
		UInt64 CreateQueryUserUGCRequest(UInt32 unAccountID, EUserUGCList eListType, EUGCMatchingUGCType eMatchingUGCType, EUserUGCListSortOrder eSortOrder, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage);
		[VTableSlot(1)]
		UInt64 CreateQueryAllUGCRequest(EUGCQuery eQueryType, EUGCMatchingUGCType eMatchingeMatchingUGCTypeFileType, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage);
		[VTableSlot(2)]
		UInt64 SendQueryUGCRequest(UInt64 handle);
		[VTableSlot(3)]
		bool GetQueryUGCResult(UInt64 handle, UInt32 index, ref SteamUGCDetails_t pDetails);
		[VTableSlot(4)]
		bool ReleaseQueryUGCRequest(UInt64 handle);
		[VTableSlot(5)]
		bool AddRequiredTag(UInt64 handle, string pTagName);
		[VTableSlot(6)]
		bool AddExcludedTag(UInt64 handle, string pTagName);
		[VTableSlot(7)]
		bool SetReturnLongDescription(UInt64 handle, bool bReturnLongDescription);
		[VTableSlot(8)]
		bool SetReturnTotalOnly(UInt64 handle, bool bReturnTotalOnly);
		[VTableSlot(9)]
		bool SetCloudFileNameFilter(UInt64 handle, string pMatchCloudFileName);
		[VTableSlot(10)]
		bool SetMatchAnyTag(UInt64 handle, bool bMatchAnyTag);
		[VTableSlot(11)]
		bool SetSearchText(UInt64 handle, string pSearchText);
		[VTableSlot(12)]
		bool SetRankedByTrendDays(UInt64 handle, UInt32 unDays);
		[VTableSlot(13)]
		UInt64 RequestUGCDetails(UInt64 nPublishedFileID);
	};
}
