// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamNetworking001")]
	public interface ISteamNetworking001
	{
		[VTableSlot(0)]
		UInt32 CreateListenSocket(Int32 nVirtualP2PPort, UInt32 nIP, UInt16 nPort);
		[VTableSlot(1)]
		UInt32 CreateP2PConnectionSocket(CSteamID steamIDTarget, Int32 nVirtualPort, Int32 nTimeoutSec);
		[VTableSlot(2)]
		UInt32 CreateConnectionSocket(UInt32 nIP, UInt16 nPort, Int32 nTimeoutSec);
		[VTableSlot(3)]
		bool DestroySocket(UInt32 hSocket, bool bNotifyRemoteEnd);
		[VTableSlot(4)]
		bool DestroyListenSocket(UInt32 hSocket, bool bNotifyRemoteEnd);
		[VTableSlot(5)]
		bool SendDataOnSocket(UInt32 hSocket, Byte[] pubData, UInt32 cubData, bool bReliable);
		[VTableSlot(6)]
		bool IsDataAvailableOnSocket(UInt32 hSocket, ref UInt32 pcubMsgSize);
		[VTableSlot(7)]
		bool RetrieveDataFromSocket(UInt32 hSocket, Byte[] pubDest, UInt32 cubDest, ref UInt32 pcubMsgSize);
		[VTableSlot(8)]
		bool IsDataAvailable(UInt32 hListenSocket, ref UInt32 pcubMsgSize, ref UInt32 phSocket);
		[VTableSlot(9)]
		bool RetrieveData(UInt32 hListenSocket, Byte[] pubDest, UInt32 cubDest, ref UInt32 pcubMsgSize);
		[VTableSlot(10)]
		bool GetSocketInfo(UInt32 hSocket, ref CSteamID pSteamIDRemote, ref Int32 peSocketStatus, ref UInt32 punIPRemote, ref UInt16 punPortRemote);
		[VTableSlot(11)]
		bool GetListenSocketInfo(UInt32 hListenSocket, ref UInt32 pnIP, ref UInt16 pnPort);
	};
}
