// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamNetworking005")]
	public interface ISteamNetworking005
	{
		[VTableSlot(0)]
		bool SendP2PPacket(CSteamID steamIDRemote, Byte[] pubData, UInt32 cubData, EP2PSend eP2PSendType, Int32 iVirtualPort);
		[VTableSlot(1)]
		bool IsP2PPacketAvailable(ref UInt32 pcubMsgSize, Int32 iVirtualPort);
		[VTableSlot(2)]
		bool ReadP2PPacket(Byte[] pubDest, UInt32 cubDest, ref UInt32 pcubMsgSize, ref CSteamID psteamIDRemote, Int32 iVirtualPort);
		[VTableSlot(3)]
		bool AcceptP2PSessionWithUser(CSteamID steamIDRemote);
		[VTableSlot(4)]
		bool CloseP2PSessionWithUser(CSteamID steamIDRemote);
		[VTableSlot(5)]
		bool CloseP2PChannelWithUser(CSteamID steamIDRemote, Int32 iVirtualPort);
		[VTableSlot(6)]
		bool GetP2PSessionState(CSteamID steamIDRemote, ref P2PSessionState_t pConnectionState);
		[VTableSlot(7)]
		bool AllowP2PPacketRelay(bool bAllow);
		[VTableSlot(8)]
		UInt32 CreateListenSocket(Int32 nVirtualP2PPort, UInt32 nIP, UInt16 nPort, bool bAllowUseOfPacketRelay);
		[VTableSlot(9)]
		UInt32 CreateP2PConnectionSocket(CSteamID steamIDTarget, Int32 nVirtualPort, Int32 nTimeoutSec, bool bAllowUseOfPacketRelay);
		[VTableSlot(10)]
		UInt32 CreateConnectionSocket(UInt32 nIP, UInt16 nPort, Int32 nTimeoutSec);
		[VTableSlot(11)]
		bool DestroySocket(UInt32 hSocket, bool bNotifyRemoteEnd);
		[VTableSlot(12)]
		bool DestroyListenSocket(UInt32 hSocket, bool bNotifyRemoteEnd);
		[VTableSlot(13)]
		bool SendDataOnSocket(UInt32 hSocket, Byte[] pubData, UInt32 cubData, bool bReliable);
		[VTableSlot(14)]
		bool IsDataAvailableOnSocket(UInt32 hSocket, ref UInt32 pcubMsgSize);
		[VTableSlot(15)]
		bool RetrieveDataFromSocket(UInt32 hSocket, Byte[] pubDest, UInt32 cubDest, ref UInt32 pcubMsgSize);
		[VTableSlot(16)]
		bool IsDataAvailable(UInt32 hListenSocket, ref UInt32 pcubMsgSize, ref UInt32 phSocket);
		[VTableSlot(17)]
		bool RetrieveData(UInt32 hListenSocket, Byte[] pubDest, UInt32 cubDest, ref UInt32 pcubMsgSize, ref UInt32 phSocket);
		[VTableSlot(18)]
		bool GetSocketInfo(UInt32 hSocket, ref CSteamID pSteamIDRemote, ref Int32 peSocketStatus, ref UInt32 punIPRemote, ref UInt16 punPortRemote);
		[VTableSlot(19)]
		bool GetListenSocketInfo(UInt32 hListenSocket, ref UInt32 pnIP, ref UInt16 pnPort);
		[VTableSlot(20)]
		ESNetSocketConnectionType GetSocketConnectionType(UInt32 hSocket);
		[VTableSlot(21)]
		Int32 GetMaxPacketSize(UInt32 hSocket);
	};
}
