// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamOAuth001")]
	public interface ISteamOAuth001
	{
		[VTableSlot(0)]
		UInt64 RequestOAuthTokenForApp(string cszOAuthScope);
		[VTableSlot(1)]
		bool GetOAuthTokenForApp(Byte[] pubBuffer, Int32 cubBuffer, ref UInt32 puTokenSize);
		[VTableSlot(2)]
		void InvalidateOAuthTokenForApp();
	};
}
