// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamUtils001")]
	public interface ISteamUtils001
	{
		[VTableSlot(0)]
		UInt32 GetSecondsSinceAppActive();
		[VTableSlot(1)]
		UInt32 GetSecondsSinceComputerActive();
		[VTableSlot(2)]
		EUniverse GetConnectedUniverse();
		[VTableSlot(3)]
		UInt32 GetServerRealTime();
	};
}
