// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamMatchMakingServers002")]
	public interface ISteamMatchmakingServers002
	{
		[VTableSlot(0)]
		TClass RequestInternetServerList<TClass>(UInt32 iApp, ref MatchMakingKeyValuePair_t ppchFilters, UInt32 nFilters, ref ISteamMatchmakingServerListResponse002 pRequestServersResponse) where TClass : class;
		[VTableSlot(1)]
		TClass RequestLANServerList<TClass>(UInt32 iApp, ref ISteamMatchmakingServerListResponse002 pRequestServersResponse) where TClass : class;
		[VTableSlot(2)]
		TClass RequestFriendsServerList<TClass>(UInt32 iApp, ref MatchMakingKeyValuePair_t ppchFilters, UInt32 nFilters, ref ISteamMatchmakingServerListResponse002 pRequestServersResponse) where TClass : class;
		[VTableSlot(3)]
		TClass RequestFavoritesServerList<TClass>(UInt32 iApp, ref MatchMakingKeyValuePair_t ppchFilters, UInt32 nFilters, ref ISteamMatchmakingServerListResponse002 pRequestServersResponse) where TClass : class;
		[VTableSlot(4)]
		TClass RequestHistoryServerList<TClass>(UInt32 iApp, ref MatchMakingKeyValuePair_t ppchFilters, UInt32 nFilters, ref ISteamMatchmakingServerListResponse002 pRequestServersResponse) where TClass : class;
		[VTableSlot(5)]
		TClass RequestSpectatorServerList<TClass>(UInt32 iApp, ref MatchMakingKeyValuePair_t ppchFilters, UInt32 nFilters, ref ISteamMatchmakingServerListResponse002 pRequestServersResponse) where TClass : class;
		[VTableSlot(6)]
		void ReleaseRequest(Byte[] hServerListRequest);
		[VTableSlot(7)]
		gameserveritem_t GetServerDetails(Byte[] hRequest, Int32 iServer);
		[VTableSlot(8)]
		void CancelQuery(Byte[] hRequest);
		[VTableSlot(9)]
		void RefreshQuery(Byte[] hRequest);
		[VTableSlot(10)]
		bool IsRefreshing(Byte[] hRequest);
		[VTableSlot(11)]
		Int32 GetServerCount(Byte[] hRequest);
		[VTableSlot(12)]
		void RefreshServer(Byte[] hRequest, Int32 iServer);
		[VTableSlot(13)]
		Int32 PingServer(UInt32 unIP, UInt16 usPort, ref ISteamMatchmakingPingResponse pRequestServersResponse);
		[VTableSlot(14)]
		Int32 PlayerDetails(UInt32 unIP, UInt16 usPort, ref ISteamMatchmakingPlayersResponse pRequestServersResponse);
		[VTableSlot(15)]
		Int32 ServerRules(UInt32 unIP, UInt16 usPort, ref ISteamMatchmakingRulesResponse pRequestServersResponse);
		[VTableSlot(16)]
		void CancelServerQuery(Int32 hServerQuery);
	};
}
