// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamFriends002")]
	public interface ISteamFriends002
	{
		[VTableSlot(0)]
		string GetPersonaName();
		[VTableSlot(1)]
		void SetPersonaName(string pchPersonaName);
		[VTableSlot(2)]
		EPersonaState GetPersonaState();
		[VTableSlot(3)]
		void SetPersonaState(EPersonaState ePersonaState);
		[VTableSlot(4)]
		Int32 GetFriendCount(EFriendFlags iFriendFlags);
		[VTableSlot(5)]
		CSteamID GetFriendByIndex(Int32 iFriend, EFriendFlags iFriendFlags);
		[VTableSlot(6)]
		EFriendRelationship GetFriendRelationship(CSteamID steamIDFriend);
		[VTableSlot(7)]
		EPersonaState GetFriendPersonaState(CSteamID steamIDFriend);
		[VTableSlot(8)]
		string GetFriendPersonaName(CSteamID steamIDFriend);
		[VTableSlot(9)]
		void SetFriendRegValue(CSteamID steamIDFriend, string pchKey, string pchValue);
		[VTableSlot(10)]
		string GetFriendRegValue(CSteamID steamIDFriend, string pchKey);
		[VTableSlot(11)]
		bool GetFriendGamePlayed(CSteamID steamIDFriend, ref UInt64 pulGameID, ref UInt32 punGameIP, ref UInt16 pusGamePort, ref UInt16 pusQueryPort);
		[VTableSlot(12)]
		string GetFriendPersonaNameHistory(CSteamID steamIDFriend, Int32 iPersonaName);
		[VTableSlot(13)]
		bool AddFriend(CSteamID steamIDFriend);
		[VTableSlot(14)]
		bool RemoveFriend(CSteamID steamIDFriend);
		[VTableSlot(15)]
		bool HasFriend(CSteamID steamIDFriend, EFriendFlags iFriendFlags);
		[VTableSlot(16)]
		Int32 AddFriendByName(string pchEmailOrAccountName);
		[VTableSlot(17)]
		bool InviteFriendByEmail(string emailAddr);
		[VTableSlot(18)]
		Int32 GetChatMessage(CSteamID steamIDFriend, Int32 iChatID, Byte[] pvData, Int32 cubData, ref EChatEntryType peFriendMsgType);
		[VTableSlot(19)]
		bool SendMsgToFriend(CSteamID steamIDFriend, EChatEntryType eFriendMsgType, Byte[] pvMsgBody, Int32 cubMsgBody);
		[VTableSlot(20)]
		Int32 GetChatIDOfChatHistoryStart(CSteamID steamIDFriend);
		[VTableSlot(21)]
		void SetChatHistoryStart(CSteamID steamIDFriend, Int32 iChatID);
		[VTableSlot(22)]
		void ClearChatHistory(CSteamID steamIDFriend);
		[VTableSlot(23)]
		Int32 GetClanCount();
		[VTableSlot(24)]
		CSteamID GetClanByIndex(Int32 iClan);
		[VTableSlot(25)]
		string GetClanName(CSteamID steamIDClan);
		[VTableSlot(26)]
		bool InviteFriendToClan(CSteamID steamIDfriend, CSteamID steamIDclan);
		[VTableSlot(27)]
		bool AcknowledgeInviteToClan(CSteamID steamID, bool arg1);
		[VTableSlot(28)]
		Int32 GetFriendCountFromSource(CSteamID steamIDSource);
		[VTableSlot(29)]
		CSteamID GetFriendFromSourceByIndex(CSteamID steamIDSource, Int32 iFriend);
	};
}
