// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamUtils002")]
	public interface ISteamUtils002
	{
		[VTableSlot(0)]
		UInt32 GetSecondsSinceAppActive();
		[VTableSlot(1)]
		UInt32 GetSecondsSinceComputerActive();
		[VTableSlot(2)]
		EUniverse GetConnectedUniverse();
		[VTableSlot(3)]
		UInt32 GetServerRealTime();
		[VTableSlot(4)]
		string GetIPCountry();
		[VTableSlot(5)]
		bool GetImageSize(Int32 iImage, ref UInt32 pnWidth, ref UInt32 pnHeight);
		[VTableSlot(6)]
		bool GetImageRGBA(Int32 iImage, Byte[] pubDest, Int32 nDestBufferSize);
		[VTableSlot(7)]
		bool GetCSERIPPort(ref UInt32 unIP, ref UInt16 usPort);
		[VTableSlot(8)]
		Byte GetCurrentBatteryPower();
	};
}
