// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamBilling001")]
	public interface ISteamBilling001
	{
		[VTableSlot(0)]
		bool SetBillingAddress(string pchName, string pchAddress1, string pchAddress2, string pchCity, string pchPostcode, string pchState, string pchCountry, string pchPhone);
		[VTableSlot(1)]
		bool GetBillingAddress(StringBuilder pchName, StringBuilder pchAddress1, StringBuilder pchAddress2, StringBuilder pchCity, StringBuilder pchPostcode, StringBuilder pchState, StringBuilder pchCountry, StringBuilder pchPhone);
		[VTableSlot(2)]
		bool SetShippingAddress(string pchName, string pchAddress1, string pchAddress2, string pchCity, string pchPostcode, string pchState, string pchCountry, string pchPhone);
		[VTableSlot(3)]
		bool GetShippingAddress(StringBuilder pchName, StringBuilder pchAddress1, StringBuilder pchAddress2, StringBuilder pchCity, StringBuilder pchPostcode, StringBuilder pchState, StringBuilder pchCountry, StringBuilder pchPhone);
		[VTableSlot(4)]
		bool GetFinalPrice(Int32 nPackageID);
		[VTableSlot(5)]
		bool SetCardInfo(ECreditCardType eCreditCardType, string pchCardNumber, string pchCardHolderName, string pchCardExpYear, string pchCardExpMonth, string pchCardCVV2);
		[VTableSlot(6)]
		bool GetCardInfo(ref ECreditCardType eCreditCardType, StringBuilder pchCardNumber, StringBuilder pchCardHolderName, StringBuilder pchCardExpYear, StringBuilder pchCardExpMonth, StringBuilder pchCardCVV2);
		[VTableSlot(7)]
		bool Purchase(Int32 nPackageID, Int32 nExpectedCostCents, UInt64 gidCardID, bool bStoreCardInfo);
	};
}
