// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMAPPS_INTERFACE_VERSION004")]
	public interface ISteamApps004
	{
		[VTableSlot(0)]
		bool BIsSubscribed();
		[VTableSlot(1)]
		bool BIsLowViolence();
		[VTableSlot(2)]
		bool BIsCybercafe();
		[VTableSlot(3)]
		bool BIsVACBanned();
		[VTableSlot(4)]
		string GetCurrentGameLanguage();
		[VTableSlot(5)]
		string GetAvailableGameLanguages();
		[VTableSlot(6)]
		bool BIsSubscribedApp(UInt32 nAppID);
		[VTableSlot(7)]
		bool BIsDlcInstalled(UInt32 nAppID);
		[VTableSlot(8)]
		UInt32 GetEarliestPurchaseUnixTime(UInt32 nAppID);
		[VTableSlot(9)]
		bool BIsSubscribedFromFreeWeekend();
		[VTableSlot(10)]
		Int32 GetDLCCount();
		[VTableSlot(11)]
		bool BGetDLCDataByIndex(Int32 iDLC, ref UInt32 pAppID, ref bool pbAvailable, StringBuilder pchName, Int32 cchNameBufferSize);
		[VTableSlot(12)]
		void InstallDLC(UInt32 nAppID);
		[VTableSlot(13)]
		void UninstallDLC(UInt32 nAppID);
	};
}
