// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMREMOTESTORAGE_INTERFACE_VERSION002")]
	public interface ISteamRemoteStorage002
	{
		[VTableSlot(0)]
		bool FileWrite(string pchFile, Byte[] pvData, Int32 cubData);
		[VTableSlot(1)]
		Int32 GetFileSize(string pchFile);
		[VTableSlot(2)]
		Int32 FileRead(string pchFile, Byte[] pvData, Int32 cubDataToRead);
		[VTableSlot(3)]
		bool FileExists(string pchFile);
		[VTableSlot(4)]
		Int32 GetFileCount();
		[VTableSlot(5)]
		string GetFileNameAndSize(Int32 iFile, ref Int32 pnFileSizeInBytes);
		[VTableSlot(6)]
		bool GetQuota(ref Int32 pnTotalBytes, ref Int32 puAvailableBytes);
	};
}
