// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamFriends006")]
	public interface ISteamFriends006
	{
		[VTableSlot(0)]
		string GetPersonaName();
		[VTableSlot(1)]
		void SetPersonaName(string pchPersonaName);
		[VTableSlot(2)]
		EPersonaState GetPersonaState();
		[VTableSlot(3)]
		Int32 GetFriendCount(EFriendFlags eFriendFlags);
		[VTableSlot(4)]
		CSteamID GetFriendByIndex(Int32 iFriend, Int32 iFriendFlags);
		[VTableSlot(5)]
		EFriendRelationship GetFriendRelationship(CSteamID steamIDFriend);
		[VTableSlot(6)]
		EPersonaState GetFriendPersonaState(CSteamID steamIDFriend);
		[VTableSlot(7)]
		string GetFriendPersonaName(CSteamID steamIDFriend);
		[VTableSlot(8)]
		Int32 GetFriendAvatar(CSteamID steamIDFriend, Int32 eAvatarSize);
		[VTableSlot(9)]
		bool GetFriendGamePlayed(CSteamID steamIDFriend, ref FriendGameInfo_t pFriendGameInfo);
		[VTableSlot(10)]
		string GetFriendPersonaNameHistory(CSteamID steamIDFriend, Int32 iPersonaName);
		[VTableSlot(11)]
		bool HasFriend(CSteamID steamIDFriend, EFriendFlags eFriendFlags);
		[VTableSlot(12)]
		Int32 GetClanCount();
		[VTableSlot(13)]
		CSteamID GetClanByIndex(Int32 iClan);
		[VTableSlot(14)]
		string GetClanName(CSteamID steamIDClan);
		[VTableSlot(15)]
		string GetClanTag(CSteamID steamIDClan);
		[VTableSlot(16)]
		Int32 GetFriendCountFromSource(CSteamID steamIDSource);
		[VTableSlot(17)]
		CSteamID GetFriendFromSourceByIndex(CSteamID steamIDSource, Int32 iFriend);
		[VTableSlot(18)]
		bool IsUserInSource(CSteamID steamIDUser, CSteamID steamIDSource);
		[VTableSlot(19)]
		void SetInGameVoiceSpeaking(CSteamID steamIDUser, bool bSpeaking);
		[VTableSlot(20)]
		void ActivateGameOverlay(string pchDialog);
		[VTableSlot(21)]
		void ActivateGameOverlayToUser(string pchDialog, CSteamID steamID);
		[VTableSlot(22)]
		void ActivateGameOverlayToWebPage(string pchURL);
		[VTableSlot(23)]
		void ActivateGameOverlayToStore(UInt32 nAppID);
		[VTableSlot(24)]
		void SetPlayedWith(CSteamID steamIDUserPlayedWith);
		[VTableSlot(25)]
		void ActivateGameOverlayInviteDialog(CSteamID steamIDLobby);
	};
}
