// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamGameCoordinator001")]
	public interface ISteamGameCoordinator001
	{
		[VTableSlot(0)]
		EGCResults SendMessage(UInt32 unMsgType, Byte[] pubData, UInt32 cubData);
		[VTableSlot(1)]
		bool IsMessageAvailable(ref UInt32 pcubMsgSize);
		[VTableSlot(2)]
		EGCResults RetrieveMessage(ref UInt32 punMsgType, Byte[] pubDest, UInt32 cubDest, ref UInt32 pcubMsgSize);
	};
}
