// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMHTTP_INTERFACE_VERSION001")]
	public interface ISteamHTTP001
	{
		[VTableSlot(0)]
		UInt32 CreateHTTPRequest(EHTTPMethod eHTTPRequestMethod, string pchAbsoluteURL);
		[VTableSlot(1)]
		bool SetHTTPRequestContextValue(UInt32 hRequest, UInt64 ulContextValue);
		[VTableSlot(2)]
		bool SetHTTPRequestNetworkActivityTimeout(UInt32 hRequest, UInt32 unTimeoutSeconds);
		[VTableSlot(3)]
		bool SetHTTPRequestHeaderValue(UInt32 hRequest, string pchHeaderName, string pchHeaderValue);
		[VTableSlot(4)]
		bool SetHTTPRequestGetOrPostParameter(UInt32 hRequest, string pchParamName, string pchParamValue);
		[VTableSlot(5)]
		bool SendHTTPRequest(UInt32 hRequest, ref UInt64 pCallHandle);
		[VTableSlot(6)]
		bool DeferHTTPRequest(UInt32 hRequest);
		[VTableSlot(7)]
		bool PrioritizeHTTPRequest(UInt32 hRequest);
		[VTableSlot(8)]
		bool GetHTTPResponseHeaderSize(UInt32 hRequest, string pchHeaderName, ref UInt32 unResponseHeaderSize);
		[VTableSlot(9)]
		bool GetHTTPResponseHeaderValue(UInt32 hRequest, string pchHeaderName, Byte[] pHeaderValueBuffer, UInt32 unBufferSize);
		[VTableSlot(10)]
		bool GetHTTPResponseBodySize(UInt32 hRequest, ref UInt32 unBodySize);
		[VTableSlot(11)]
		bool GetHTTPResponseBodyData(UInt32 hRequest, Byte[] pBodyDataBuffer, UInt32 unBufferSize);
		[VTableSlot(12)]
		bool ReleaseHTTPRequest(UInt32 hRequest);
		[VTableSlot(13)]
		bool GetHTTPDownloadProgressPct(UInt32 hRequest, ref float pflPercentOut);
		[VTableSlot(14)]
		bool SetHTTPRequestRawPostBody(UInt32 hRequest, string pchContentType, Byte[] pubBody, UInt32 unBodyLen);
	};
}
