// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamUser012")]
	public interface ISteamUser012
	{
		[VTableSlot(0)]
		Int32 GetHSteamUser();
		[VTableSlot(1)]
		bool BLoggedOn();
		[VTableSlot(2)]
		CSteamID GetSteamID();
		[VTableSlot(3)]
		Int32 InitiateGameConnection(Byte[] pAuthBlob, Int32 cbMaxAuthBlob, CSteamID steamIDGameServer, UInt32 unIPServer, UInt16 usPortServer, bool bSecure);
		[VTableSlot(4)]
		void TerminateGameConnection(UInt32 unIPServer, UInt16 usPortServer);
		[VTableSlot(5)]
		void TrackAppUsageEvent(CGameID gameID, EAppUsageEvent eAppUsageEvent, string pchExtraInfo);
		[VTableSlot(6)]
		bool GetUserDataFolder(StringBuilder pchBuffer, Int32 cubBuffer);
		[VTableSlot(7)]
		void StartVoiceRecording();
		[VTableSlot(8)]
		void StopVoiceRecording();
		[VTableSlot(9)]
		EVoiceResult GetCompressedVoice(Byte[] pDestBuffer, UInt32 cbDestBufferSize, ref UInt32 nBytesWritten);
		[VTableSlot(10)]
		EVoiceResult DecompressVoice(Byte[] pCompressed, UInt32 cbCompressed, Byte[] pDestBuffer, UInt32 cbDestBufferSize, ref UInt32 nBytesWritten);
		[VTableSlot(11)]
		UInt32 GetAuthSessionTicket(Byte[] pTicket, Int32 cbMaxTicket, ref UInt32 pcbTicket);
		[VTableSlot(12)]
		EBeginAuthSessionResult BeginAuthSession(Byte[] pAuthTicket, Int32 cbAuthTicket, CSteamID steamID);
		[VTableSlot(13)]
		void EndAuthSession(CSteamID steamID);
		[VTableSlot(14)]
		void CancelAuthTicket(UInt32 hAuthTicket);
		[VTableSlot(15)]
		EUserHasLicenseForAppResult UserHasLicenseForApp(CSteamID steamID, UInt32 appID);
	};
}
