// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMMUSIC_INTERFACE_VERSION001")]
	public interface ISteamMusic001
	{
		[VTableSlot(0)]
		Int32 BIsEnabled();
		[VTableSlot(1)]
		Int32 BIsPlaying();
		[VTableSlot(2)]
		Int32 GetPlaybackStatus();
		[VTableSlot(3)]
		Int32 Play();
		[VTableSlot(4)]
		Int32 Pause();
		[VTableSlot(5)]
		Int32 PlayPrevious();
		[VTableSlot(6)]
		Int32 PlayNext();
		[VTableSlot(7)]
		Int32 SerVolume(float fUnk);
		[VTableSlot(8)]
		Int32 GetVolume();
	};
}
