// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public enum EUGCQuery : int
	{
	};
	
	public enum EUserUGCList : int
	{
	};
	
	public enum EUGCMatchingUGCType : int
	{
	};
	
	public enum EUserUGCListSortOrder : int
	{
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct SteamUGCDetails_t
	{
		public Int32 m_iPadding;
	};
	
}
